# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://sounding.com/"
DefaultContentLanguage  = "en"
title                   = "Sounding"
theme                   = "hugo-future-imperfect-slim"
paginate                = 5
disqusShortname         = ""
googleAnalytics         = "UA-27675542-1"
pluralizeListTitles     = false
disableLanguages        = []
enableEmoji             = true

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = "h"
  removeBlur            = false
  socialShare           = ["twitter", "linkedin", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "HTML5UP and Hugo"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Sounding"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "Sounding"
    paragraph             = "Complexity / Music / Technology / Intuition / Poetry / Listening"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/sideface.jpg"
      shape               = "hexagon"
      width               = ""
      alt                 = "Sounding"

  [params.sidebar]
    postAmount          = 3
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Features"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-music'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-keyboard'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Improv"
    identifier        = "improv"
    url               = "/improv/"
    pre               = "<i class='far fa-book-open'></i>"
    weight            = 3

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-infinity'></i>"
    weight            = 4

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  github                = "maroda"
  linkedin              = "mattcookedavis"
  facebook              = "craque"
  youtube               = "dtauvdiodr"
  instagram             = "dtauvdiodr"
  twitter               = "dtauvdiodr"
  email                 = "maroda@gmail.com"
